import StaticPageShell from '@/components/uae/StaticPageShell';
import styles from '@/components/uae/StaticPageShell.module.css';

const LAST_UPDATED = 'June 28, 2026';

const LEGAL_SECTIONS = [
  {
    id: 'independence-non-affiliation',
    title: 'Independence & Non-Affiliation',
    body:
      'Discover the Emirates is an independent travel guide and is not affiliated with, endorsed by, or connected to the Government of the United Arab Emirates, the Emirates Group, Emirates Airline, or any other entity using the name "Emirates." All views, content, and recommendations on this site are our own.',
  },
  {
    id: 'ai-generated-content',
    title: 'AI-Generated Content',
    body:
      'Itineraries generated by our AI planner are suggestions based on available data at the time of generation. They are not guarantees of accuracy, availability, or suitability. Please verify opening hours, prices, and availability independently before relying on any plan.',
  },
  {
    id: 'affiliate-commission-disclosure',
    title: 'Affiliate & Commission Disclosure',
    body:
      'Some hotel links on this site are affiliate links. We may earn a commission when you book through them, at no additional cost to you. This does not affect which properties we choose to feature.',
  },
  {
    id: 'not-official-tourism-resource',
    title: 'Not an Official Tourism Resource',
    body:
      'This site is an independent travel guide and is not an official government or tourism authority resource. For visa, customs, entry requirements, and other official matters, please consult the UAE government\'s official channels (e.g., u.ae) or your nearest UAE embassy or consulate.',
  },
  {
    id: 'pricing-availability',
    title: 'Pricing & Availability',
    body:
      'Hotel prices and availability shown are accurate as of the date they were retrieved and may change. Always confirm current pricing and availability directly with the hotel or booking provider before completing a reservation.',
  },
  {
    id: 'ai-itinerary-credits',
    title: 'AI Itinerary Credits — Payment & Refunds',
    body:
      'Each paid itinerary credit unlocks one AI-generated itinerary. If a generation fails due to a technical error on our part, contact camanupandit75@gmail.com for a refund. Credits are non-transferable and have no cash value outside their intended use.',
  },
  {
    id: 'privacy',
    title: 'Privacy',
    body:
      'We use Stripe to process payments securely; we do not store your payment card details. Contact form submissions are used only to respond to your inquiry. We do not sell your personal information.',
  },
  {
    id: 'third-party-content',
    title: 'Third-Party Content',
    body:
      'YouTube videos and links featured on this site are the property of their respective creators and platforms. We do not own, control, or endorse third-party video content, and its inclusion does not imply affiliation.',
  },
];

export const metadata = {
  title: 'Legal & Disclaimers — Discover the Emirates',
  description:
    'Legal disclaimers for Discover the Emirates — independence, AI content, affiliate links, pricing, privacy, and more.',
};

export default function LegalPage() {
  return (
    <StaticPageShell
      eyebrow="Legal"
      title="Legal & Disclaimers"
      intro="This page summarizes important disclaimers for using Discover the Emirates. It is informational only and does not constitute legal advice."
    >
      <p className={styles.lastUpdated}>Last updated: {LAST_UPDATED}</p>

      {LEGAL_SECTIONS.map((section) => (
        <section
          key={section.id}
          id={section.id}
          className={styles.contentSection}
        >
          <div className={styles.sectionHeader}>
            <span className={styles.tickRule} aria-hidden="true" />
            <h2 className={styles.sectionTitle}>{section.title}</h2>
          </div>
          <p className={styles.prose}>{section.body}</p>
        </section>
      ))}
    </StaticPageShell>
  );
}
